-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 23:13:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_ANCA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_ANCA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_ANCA` DEFAULT CHARACTER SET utf8 ;
USE `BD_ANCA` ;

-- -----------------------------------------------------
-- Table `BD_ANCA`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ANCA`.`Clientes` (
  `idCliente` INT(10) NOT NULL AUTO_INCREMENT,
  `ApellidoP` VARCHAR(20) NOT NULL,
  `ApellidoM` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tel` INT(15) NOT NULL,
  `Correo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ANCA`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ANCA`.`Material` (
  `idMaterial` INT(10) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ANCA`.`Tipo_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ANCA`.`Tipo_material` (
  `idTipo_material` VARCHAR(100) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ANCA`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ANCA`.`Compra` (
  `idCompra` INT(10) NOT NULL AUTO_INCREMENT,
  `idCliente` INT(10) NOT NULL,
  `idMaterial` INT(10) NOT NULL,
  `Cantidad` INT(10) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `idMaterial_idx` (`idMaterial` ASC) VISIBLE,
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `Tipo_idx` (`Tipo` ASC) VISIBLE,
  CONSTRAINT `idMaterial`
    FOREIGN KEY (`idMaterial`)
    REFERENCES `BD_ANCA`.`Material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `BD_ANCA`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tipo`
    FOREIGN KEY (`Tipo`)
    REFERENCES `BD_ANCA`.`Tipo_material` (`idTipo_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
