DROP DATABASE IF EXIST anca_base;
CREATE DATABASE ANCA;
USE ANCA;

CREATE TABLE TIPO_MATERIAL{
	  `idTipo_material` VARCHAR(100) PRIMARY KEY NOT NULL,
 	 `Tipo` VARCHAR(45) NOT NULL,	
};
CREATE TABLE MATERIAL{
	  `idMaterial` INT(10) PRIMARY KEY NOT NULL,
	  `Tipo` VARCHAR(45) NOT NULL,
	  `Nombre` VARCHAR(45) NOT NULL,
	   `idTipo_material` INT(10) NOT NULL,
	FOREGIN KEY (idTipo_material) REFERENCES CLIENTE (idTipo_material)
		ON UPDATE CASCADE
};
INSERT INTO CLIENTES VALUES ('FERRETERIA','MARTILLOS');
INSERT INTO CLIENTES VALUES ('DEPORTES','BALONES');
INSERT INTO CLIENTES VALUES ('PAPELERIA','HOJAS BLANCAS');